# Copyright 2025, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Build opensource projects

permissions: read-all

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'snap/**'
      - 'benchmarks/**'
      - 'tests/**'
      - 'examples/**'
      - 'tools/**'
      - 'utils/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ispc:
    name: Build ISPC
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: true

    - name: Install ISPC build dependencies
      run: .github/workflows/scripts/install-build-deps.sh

    - name: Build ISPC
      run: .github/workflows/scripts/build-ispc.sh

    - name: Upload ISPC artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ispc-fresh-build
        path: build/ispc-trunk-linux.tar.gz

  build-open3d:
    name: Build Open3D
    needs: build-ispc
    runs-on: ubuntu-22.04
    # Needs patching to be built, because it uses the specific ISPC version and
    # removed target (knl)
    if: false
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake ninja

    - name: Create build user
      run: |
        useradd -m -G wheel -s /bin/bash builder
        echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    # Build and install the required dependency for Open3D from AUR
    - name: Build and install python-dash
      run: |
        su - builder -c "
          git clone https://aur.archlinux.org/python-dash.git
          cd python-dash/
          makepkg -si --noconfirm
        "

    - name: Build and install nanoflann
      run: |
        su - builder -c "
          git clone https://aur.archlinux.org/nanoflann.git
          cd nanoflann
          makepkg -si --noconfirm
        "

    - name: Build Open3D
      run: |
        su - builder -c "
          git clone https://aur.archlinux.org/open3d.git
          cd open3d
          sed -i "s/'ispc'//" PKGBUILD
          makepkg -s --noconfirm
        "

  build-nbody:
    name: Build hfisher/nbody
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake mercurial ninja

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build hfisher/nbody
      run: |
        hg clone  https://hg.sr.ht/~hfisher/nbody
        cd nbody
        sed -i 's/BUILD_ISPC 0/BUILD_ISPC 1/' CMakeLists.txt
        cmake -S ./ -B build -G Ninja
        cmake --build build

  build-ISPCTextureCompressor:
    name: Build ISPCTextureCompressor
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build ISPCTextureCompressor
      run: |
        git clone https://github.com/GameTechDev/ISPCTextureCompressor.git
        cd ISPCTextureCompressor/
        make -f Makefile.linux ISPC_ARCH=x86_64 ISPC_TARGETS=sse2,avx2,avx512skx-x16 ISPC=/usr/local/bin/ispc

  build-lc0:
    name: Build Leela Chess lc0
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake gtest

    - name: Create build user
      run: |
        useradd -m -G wheel -s /bin/bash builder
        echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build Leela Chess lc0
      run: |
        su - builder -c "
          git clone https://aur.archlinux.org/lc0.git
          cd lc0
          makepkg -s --noconfirm
        "

  build-GPSnoopy-RayTracingInOneWeekend:
    name: Build GPSnoopy/RayTracingInOneWeekend
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake ninja

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build GPSnoopy/RayTracingInOneWeekend
      run: |
        git clone https://github.com/GPSnoopy/RayTracingInOneWeekend.git
        cmake -G Ninja -B build -S RayTracingInOneWeekend/ispc
        cmake --build build --verbose

  build-ispc-upwind:
    name: Build ispc-upwind
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build ispc-upwind
      run: |
        git clone https://gitlab.com/rossinelli/ispc-upwind.git
        cd ispc-upwind/
        make
        make TARGET=sse4,avx2,avx512skx-x16

  build-flash-attention-gpt-on-cpu:
    name: Build FlashAttentionGPTonCPU
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build FlashAttentionGPTonCPU
      run: |
        git clone https://github.com/ZipXuan/FlashAttentionGPTonCPU.git
        cd FlashAttentionGPTonCPU/
        ispc -O3 --target=avx2-i32x8 --arch=x86-64 --pic module.ispc -h module_ispc.h -o module_ispc.o

  build-merle:
    name: Build merle
    needs: build-ispc
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Setup Arch Linux
      run: |
        pacman -Syu --noconfirm
        pacman -S --needed --noconfirm base-devel git sudo cmake ninja

    - name: Download fresh ISPC
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ispc-fresh-build
        path: /tmp/ispc-build

    - name: Install fresh ISPC
      run: |
        cd /tmp/ispc-build
        tar -xzf ispc-trunk-linux.tar.gz
        cp -r ispc-trunk-linux/bin/* /usr/local/bin/
        chmod +x /usr/local/bin/ispc
        ispc --version

    - name: Build merle
      run: |
        git clone --recursive https://github.com/chinmaygarde/merle.git
        cd merle/
        sed -i '/add_custom_command(/,/DEPENDS src\/texture.ispc/ s/--werror/--werror\n                          --pic/' CMakeLists.txt
        git diff
        cmake -B build -S ./ -G Ninja
        cmake --build build
