# Copyright 2023-2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Sanitizers

permissions: read-all

on:
  pull_request:
  workflow_dispatch:

env:
  SDE_MIRROR_ID: 813591
  SDE_TAR_NAME: sde-external-9.33.0-2024-01-07
  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
  LLVM_REPO: https://github.com/ispc/ispc.dependencies

jobs:
  linux-ispc-llvm17-asan:
    runs-on: ubuntu-latest
    env:
      LLVM_VERSION: "17.0"
      LLVM_TAR: llvm-17.0.6-ubuntu18.04-Release+Asserts-x86.arm.wasm.tar.xz
      ISPC_OPAQUE_PTR_MODE: "ON"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        .github/workflows/scripts/install-build-deps.sh

    - name: Check environment
      run: |
        which -a gcc
        cat /proc/cpuinfo

    - name: Build ISPC with ASAN
      run: |
          cmake -B build \
              -DISPC_USE_LLVM_LIBCXX=ON \
              -DISPC_STATIC_LIBSTDCXX=ON \
              -DCMAKE_C_FLAGS="-fsanitize=address -O0 -g3" \
              -DCMAKE_CXX_FLAGS="-fsanitize=address -O0 -g3"
          cmake --build build --target ispc ispc-opt -j4

    - name: Build examples with ASAN
      run: |
          ASAN_OPTIONS=detect_leaks=1 cmake --build build --target ispc_cpu_examples -j4

    - name: Build LIT tests with ASAN
      run: |
          ASAN_OPTIONS=detect_leaks=1 cmake --build build --target check-all

    - name: Build runtime tests with ASAN
      run: |
          ASAN_OPTIONS=detect_leaks=1 PATH=`pwd`/build/bin:$PATH ./run_tests.py --target=avx2-i32x8 --arch=x86-64
