# Copyright 2025, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

# These jobs build ISPC for trunk on every push to main pushing artifacts to
# pre-release.
name: Trunk Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  LLVM_REPO: https://github.com/ispc/ispc.dependencies
  ISPC_HOME: ${{ github.workspace }}
  LLVM_HOME: ${{ github.workspace }}
  LLVM_VERSION: "18.1"

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Needed for release creation/update

    env:
      LLVM_TAR: llvm-18.1.8-ubuntu22.04-Release+Asserts-x86.arm.wasm.tar.xz

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        submodules: false

    - name: Install Dependencies
      run: |
        .github/workflows/scripts/install-build-deps.sh

    - name: Configure
      run: |
        # Setup emcc for WASM target
        source scripts/install_emscripten.sh && emcc --version
        cmake -B build ./ -DISPC_PREPARE_PACKAGE=ON -DCMAKE_INSTALL_PREFIX="$ISPC_HOME"/install -DISPC_CROSS=ON -DWASM_ENABLED=ON -DCMAKE_CXX_FLAGS="-Werror"

    - name: Build
      run: cd build && make package -j"$(nproc)"

    - name: Upload Artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ispc-linux
        path: build/ispc-*
      
    - name: Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # 2.2.1
      with:
        name: trunk-artifacts
        tag_name: trunk-artifacts
        files: build/ispc-*.tar.gz
        draft: false
        prerelease: true
        body: "Automatically updated trunk artifacts"
        fail_on_unmatched_files: true
        generate_release_notes: false
        append_body: false

  windows:
    runs-on: windows-2019
    env:
      CROSS_TOOLS_GNUWIN32: "C:\\projects\\cross\\gnuwin32"
      LLVM_TAR: llvm-18.1.8-win.vs2019-Release+Asserts-x86.arm.wasm.tar.7z

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        submodules: false

    - name: Install dependencies
      run: |
        .github/workflows/scripts/install-build-deps.ps1

    - name: Build and Test
      shell: cmd
      run: |
        call scripts\install_emscripten.bat
        set VSVARS="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        call %VSVARS%
        cmake . -B build -Thost=x64 -G "Visual Studio 16" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%ISPC_HOME%\install -DISPC_PREPARE_PACKAGE=ON -DISPC_CROSS=ON -DISPC_GNUWIN32_PATH=%CROSS_TOOLS_GNUWIN32% -DWASM_ENABLED=ON -DISPC_INCLUDE_BENCHMARKS=ON
        cmake --build build --config Release --target package --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ispc-windows
        path: build/ispc-*-windows.zip

    - name: Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # 2.2.1
      with:
        name: trunk-artifacts
        tag_name: trunk-artifacts
        files: build/ispc-*.windows.zip
        draft: false
        prerelease: true
        body: "Automatically updated trunk artifacts"
        fail_on_unmatched_files: true
        generate_release_notes: false
        append_body: false
